<a href="https://colab.research.google.com/github/Bhargavimarathe/BhargaviMarathe/blob/main/daily_codes/week4/pandas_jun15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas

In [ ]:
# 1D data structure in pandas

In [ ]:
# pandas series is a one dimensional array capableof holding any data type

In [ ]:
# creating  pandas series

In [ ]:
import pandas as pd

In [ ]:
s= pd.Series([10,20,30])

In [ ]:
s

0    10
1    20
2    30
dtype: int64

In [ ]:
s= pd.Series([22,44,66,88])

In [ ]:
s

0    22
1    44
2    66
3    88
dtype: int64

In [ ]:
# with custom index

In [ ]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s = pd.Series(['bhargavi', 18, 93.42], index=['name', 'age', 'marks'])

In [ ]:
s

name     bhargavi
age            18
marks       93.42
dtype: object

In [ ]:
# from dictionary

In [ ]:
data = {'name':"bhargavi",'age':18,'marks': 92.59}

In [ ]:
data

{'name': 'bhargavi', 'age': 18, 'marks': 92.59}

In [ ]:
s= pd.Series(data)

In [ ]:
s

name     bhargavi
age            18
marks       92.59
dtype: object

In [ ]:
data = {'name':"bhargavi",'sub':"DSU",'year': 'SY','marks': 100}

In [ ]:
s=pd.Series(data)

In [ ]:
s

name     bhargavi
sub           DSU
year           SY
marks         100
dtype: object

In [ ]:
# from a single value

In [ ]:
s = pd.Series(5, index=[0,1,2,3])

In [ ]:
s

0    5
1    5
2    5
3    5
dtype: int64

In [ ]:
#attributes

In [ ]:
s=pd.Series([10,20,30], index=['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s.values

array([10, 20, 30])

In [ ]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.size

3

In [ ]:
s.shape

(3,)

In [ ]:
# data manipulation

In [ ]:
s=  pd.Series([1,2,3,4,])

In [ ]:
print(s*3)

0     3
1     6
2     9
3    12
dtype: int64

In [ ]:
print(s+3)

0    4
1    5
2    6
3    7
dtype: int64

In [ ]:
# handeling missing values

In [ ]:
s=pd.Series([1,None,3])

In [ ]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

In [ ]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [ ]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [ ]:
s.fillna(0)

0    1.0
1    0.0
2    3.0
dtype: float64

In [ ]:
# indexing

In [ ]:
s = pd.Series([10,20,30], index=['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s['a']

np.int64(10)

In [ ]:
s['c']

np.int64(30)