<a href="https://colab.research.google.com/github/Bhargavimarathe/BhargaviMarathe/blob/main/daily_codes/week4/pandas_dataframe_jun17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
roll = pd.Series([1,2,3,4,5])
name= pd.Series(['sia','riya','bhargavi','ravi','geet'])
marks= pd.Series([85,67,59,40,90])

In [ ]:
df= pd.DataFrame({
    'id': roll,
    'name': name,
    'marks': marks
})

In [ ]:
df

   id      name  marks
0   1       sia     85
1   2      riya     67
2   3  bhargavi     59
3   4      ravi     40
4   5      geet     90

In [ ]:
df.shape

(5, 3)

In [ ]:
df.size

15

In [ ]:
df.ndim

2

In [ ]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [ ]:
"""
url -> https:// mitu.co.in/dataset
download all the datasets starting with student*
put them in the same file folder as your current working directory
""";

In [ ]:
pwd

'/content'

In [ ]:
df= pd.read_csv("student.csv")

In [ ]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [ ]:
df.shape

(10, 5)

In [ ]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [ ]:
# student1.csv

In [ ]:
df= pd.read_csv('student1.csv')

In [ ]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [ ]:
col=['roll','name','class','marks','age']

In [ ]:
df=pd.read_csv('student1.csv',names=col)

In [ ]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [ ]:
# student3.tsv

In [ ]:
df = pd.read_csv('student3.tsv', sep='\t')

In [ ]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21