<a href="https://colab.research.google.com/github/Bhargavimarathe/BhargaviMarathe/blob/main/daily_codes/week5/data_cleaning_jun22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# student3.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv("student3.csv")

In [ ]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [ ]:
df.shape

(16, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 772.0+ bytes

In [ ]:
df.size

80

In [ ]:
# fix structural error

In [ ]:
df['name']

0        anil
1        amit
2      aniket
3     ajinkya
4        asha
5      ayesha
6        amar
7       Amita
8        amol
9        amol
10      anmol
11     surbhi
12      Sujay
13    subhash
14     sachin
15    shalini
Name: name, dtype: object

In [ ]:
df['name']= df['name'].str.title()

In [ ]:
df

    roll     name  class  marks    age
0      1     Anil    NaN   56.77  22.0
1      2     Amit    NaN   59.77  21.0
2      3   Aniket    NaN   76.88  19.0
3      4  Ajinkya    NaN   69.66  20.0
4      5     Asha    NaN   63.28   NaN
5      6   Ayesha    NaN     NaN  20.0
6      7     Amar    NaN   65.34  19.0
7      8    Amita    NaN   68.33  23.0
8      9     Amol    NaN   56.75  20.0
9      9     Amol    NaN   56.75  20.0
10    10    Anmol    NaN   78.66   NaN
11    11   Surbhi    NaN     NaN  23.0
12    12    Sujay    NaN   74.12  22.0
13    13  Subhash    NaN   88.45  21.0
14    14   Sachin    NaN   59.33  21.0
15    15  Shalini    NaN   63.45  20.0

In [ ]:
df

    roll     name  class  marks    age
0      1     Anil    NaN   56.77  22.0
1      2     Amit    NaN   59.77  21.0
2      3   Aniket    NaN   76.88  19.0
3      4  Ajinkya    NaN   69.66  20.0
4      5     Asha    NaN   63.28   NaN
5      6   Ayesha    NaN     NaN  20.0
6      7     Amar    NaN   65.34  19.0
7      8    Amita    NaN   68.33  23.0
8      9     Amol    NaN   56.75  20.0
9      9     Amol    NaN   56.75  20.0
10    10    Anmol    NaN   78.66   NaN
11    11   Surbhi    NaN     NaN  23.0
12    12    Sujay    NaN   74.12  22.0
13    13  Subhash    NaN   88.45  21.0
14    14   Sachin    NaN   59.33  21.0
15    15  Shalini    NaN   63.45  20.0

In [ ]:
df['class'] = [
    'TE', 'TE', 'BE', 'TE', 'TE',
    'BE', 'BE', 'BE', 'TE', 'TE',
    'BE', 'TE', 'TE', 'BE',
    np.nan, 'TE'
]

In [ ]:
df.to_csv('student3.csv', index=False)

In [ ]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    BE   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    BE   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [ ]:
df['marks']

KeyError: 'marks'

In [ ]:
df.columns

Index(['roll', 'name', 'class', 'marks ', 'age'], dtype='object')

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [ ]:
df['marks']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [ ]:
# duplicate values

In [ ]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [ ]:
## another method (df.drop_duplicates(inplace=True))

In [ ]:
df.count()

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [ ]:
df.isnull().sum()

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(5)

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'roll': [1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 10, 11, 12, 13, 14, 15],
    'name': ['anil', 'amit', 'aniket', 'ajinkya', 'asha', 'ayesha',
             'amar', 'Amita', 'amol', 'amol', 'anmol', 'surbhi',
             'Sujay', 'subhash', 'sachin', 'shalini'],
    'class': ['TE', 'TE', 'BE', 'TE', 'TE', 'BE',
              'BE', 'be', 'TE', 'TE', 'BE', 'TE',
              'TE', 'be', np.nan, 'TE'],
    'marks': [56.77, 59.77, 76.88, 69.66, 63.28, np.nan,
              65.34, 68.33, 56.75, 56.75, 78.66, np.nan,
              74.12, 88.45, 59.33, 63.45],
    'age': [22.0, 21.0, 19.0, 20.0, np.nan, 20.0,
            19.0, 23.0, 20.0, 20.0, np.nan, 23.0,
            22.0, 21.0, 21.0, 20.0]
})

In [ ]:
df

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
4      5     asha    TE  63.28   NaN
5      6   ayesha    BE    NaN  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
9      9     amol    TE  56.75  20.0
10    10    anmol    BE  78.66   NaN
11    11   surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
14    14   sachin   NaN  59.33  21.0
15    15  shalini    TE  63.45  20.0

In [ ]:
df.to_csv('student3.csv', index=False)

In [ ]:
df

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
4      5     asha    TE  63.28   NaN
5      6   ayesha    BE    NaN  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
9      9     amol    TE  56.75  20.0
10    10    anmol    BE  78.66   NaN
11    11   surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
14    14   sachin   NaN  59.33  21.0
15    15  shalini    TE  63.45  20.0

In [ ]:
# removing rows with null values

In [ ]:
df.dropna()

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
9      9     amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
15    15  shalini    TE  63.45  20.0

In [ ]:
# filling the missing values

In [ ]:
df['marks'].fillna(45)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     45.00
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11    45.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [ ]:
# fill with avg marks

In [ ]:
df['marks'].fillna(df['marks'].mean())

0     56.770000
1     59.770000
2     76.880000
3     69.660000
4     63.280000
5     66.967143
6     65.340000
7     68.330000
8     56.750000
9     56.750000
10    78.660000
11    66.967143
12    74.120000
13    88.450000
14    59.330000
15    63.450000
Name: marks, dtype: float64

In [ ]:
# fill age with median

In [ ]:
df['age'].fillna(df['age'].median())

0     22.0
1     21.0
2     19.0
3     20.0
4     20.5
5     20.0
6     19.0
7     23.0
8     20.0
9     20.0
10    20.5
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [ ]:
df['class'].str.upper()

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      BE
8      TE
9      TE
10     BE
11     TE
12     TE
13     BE
14    NaN
15     TE
Name: class, dtype: object

In [ ]:
# fill class column value with mode

In [ ]:
df['class'].fillna(df['class'].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     be
8     TE
9     TE
10    BE
11    TE
12    TE
13    be
14    TE
15    TE
Name: class, dtype: object

In [ ]:
df.ffill()

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
4      5     asha    TE  63.28  20.0
5      6   ayesha    BE  63.28  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
9      9     amol    TE  56.75  20.0
10    10    anmol    BE  78.66  20.0
11    11   surbhi    TE  78.66  23.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
14    14   sachin    be  59.33  21.0
15    15  shalini    TE  63.45  20.0

In [ ]:
df.bfill(inplace=True)

In [ ]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64